/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yunda.realtime.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BeiDouSystem extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8211404078244440567L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BeiDouSystem\",\"namespace\":\"com.yunda.realtime.avro\",\"fields\":[{\"name\":\"depart_proof\",\"type\":[\"string\",\"null\"]},{\"name\":\"site_type\",\"type\":[\"int\",\"null\"]},{\"name\":\"site_encoding\",\"type\":[\"string\",\"null\"]},{\"name\":\"loadometer_load_gross_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"loadometer_load_net_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"loadometer_unload_gross_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"loadometer_unload_net_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"loadometer_load_unload_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"scan_load_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"load_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"scan_unload_weight\",\"type\":[\"double\",\"null\"]},{\"name\":\"unload_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"database_timestamp\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BeiDouSystem> ENCODER =
      new BinaryMessageEncoder<BeiDouSystem>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BeiDouSystem> DECODER =
      new BinaryMessageDecoder<BeiDouSystem>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BeiDouSystem> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BeiDouSystem> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BeiDouSystem>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BeiDouSystem to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BeiDouSystem from a ByteBuffer. */
  public static BeiDouSystem fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence depart_proof;
  @Deprecated public java.lang.Integer site_type;
  @Deprecated public java.lang.CharSequence site_encoding;
  @Deprecated public java.lang.Double loadometer_load_gross_weight;
  @Deprecated public java.lang.Double loadometer_load_net_weight;
  @Deprecated public java.lang.Double loadometer_unload_gross_weight;
  @Deprecated public java.lang.Double loadometer_unload_net_weight;
  @Deprecated public java.lang.Double loadometer_load_unload_weight;
  @Deprecated public java.lang.Double scan_load_weight;
  @Deprecated public java.lang.Integer load_number;
  @Deprecated public java.lang.Double scan_unload_weight;
  @Deprecated public java.lang.Integer unload_number;
  @Deprecated public java.lang.Long database_timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BeiDouSystem() {}

  /**
   * All-args constructor.
   * @param depart_proof The new value for depart_proof
   * @param site_type The new value for site_type
   * @param site_encoding The new value for site_encoding
   * @param loadometer_load_gross_weight The new value for loadometer_load_gross_weight
   * @param loadometer_load_net_weight The new value for loadometer_load_net_weight
   * @param loadometer_unload_gross_weight The new value for loadometer_unload_gross_weight
   * @param loadometer_unload_net_weight The new value for loadometer_unload_net_weight
   * @param loadometer_load_unload_weight The new value for loadometer_load_unload_weight
   * @param scan_load_weight The new value for scan_load_weight
   * @param load_number The new value for load_number
   * @param scan_unload_weight The new value for scan_unload_weight
   * @param unload_number The new value for unload_number
   * @param database_timestamp The new value for database_timestamp
   */
  public BeiDouSystem(java.lang.CharSequence depart_proof, java.lang.Integer site_type, java.lang.CharSequence site_encoding, java.lang.Double loadometer_load_gross_weight, java.lang.Double loadometer_load_net_weight, java.lang.Double loadometer_unload_gross_weight, java.lang.Double loadometer_unload_net_weight, java.lang.Double loadometer_load_unload_weight, java.lang.Double scan_load_weight, java.lang.Integer load_number, java.lang.Double scan_unload_weight, java.lang.Integer unload_number, java.lang.Long database_timestamp) {
    this.depart_proof = depart_proof;
    this.site_type = site_type;
    this.site_encoding = site_encoding;
    this.loadometer_load_gross_weight = loadometer_load_gross_weight;
    this.loadometer_load_net_weight = loadometer_load_net_weight;
    this.loadometer_unload_gross_weight = loadometer_unload_gross_weight;
    this.loadometer_unload_net_weight = loadometer_unload_net_weight;
    this.loadometer_load_unload_weight = loadometer_load_unload_weight;
    this.scan_load_weight = scan_load_weight;
    this.load_number = load_number;
    this.scan_unload_weight = scan_unload_weight;
    this.unload_number = unload_number;
    this.database_timestamp = database_timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return depart_proof;
    case 1: return site_type;
    case 2: return site_encoding;
    case 3: return loadometer_load_gross_weight;
    case 4: return loadometer_load_net_weight;
    case 5: return loadometer_unload_gross_weight;
    case 6: return loadometer_unload_net_weight;
    case 7: return loadometer_load_unload_weight;
    case 8: return scan_load_weight;
    case 9: return load_number;
    case 10: return scan_unload_weight;
    case 11: return unload_number;
    case 12: return database_timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: depart_proof = (java.lang.CharSequence)value$; break;
    case 1: site_type = (java.lang.Integer)value$; break;
    case 2: site_encoding = (java.lang.CharSequence)value$; break;
    case 3: loadometer_load_gross_weight = (java.lang.Double)value$; break;
    case 4: loadometer_load_net_weight = (java.lang.Double)value$; break;
    case 5: loadometer_unload_gross_weight = (java.lang.Double)value$; break;
    case 6: loadometer_unload_net_weight = (java.lang.Double)value$; break;
    case 7: loadometer_load_unload_weight = (java.lang.Double)value$; break;
    case 8: scan_load_weight = (java.lang.Double)value$; break;
    case 9: load_number = (java.lang.Integer)value$; break;
    case 10: scan_unload_weight = (java.lang.Double)value$; break;
    case 11: unload_number = (java.lang.Integer)value$; break;
    case 12: database_timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'depart_proof' field.
   * @return The value of the 'depart_proof' field.
   */
  public java.lang.CharSequence getDepartProof() {
    return depart_proof;
  }

  /**
   * Sets the value of the 'depart_proof' field.
   * @param value the value to set.
   */
  public void setDepartProof(java.lang.CharSequence value) {
    this.depart_proof = value;
  }

  /**
   * Gets the value of the 'site_type' field.
   * @return The value of the 'site_type' field.
   */
  public java.lang.Integer getSiteType() {
    return site_type;
  }

  /**
   * Sets the value of the 'site_type' field.
   * @param value the value to set.
   */
  public void setSiteType(java.lang.Integer value) {
    this.site_type = value;
  }

  /**
   * Gets the value of the 'site_encoding' field.
   * @return The value of the 'site_encoding' field.
   */
  public java.lang.CharSequence getSiteEncoding() {
    return site_encoding;
  }

  /**
   * Sets the value of the 'site_encoding' field.
   * @param value the value to set.
   */
  public void setSiteEncoding(java.lang.CharSequence value) {
    this.site_encoding = value;
  }

  /**
   * Gets the value of the 'loadometer_load_gross_weight' field.
   * @return The value of the 'loadometer_load_gross_weight' field.
   */
  public java.lang.Double getLoadometerLoadGrossWeight() {
    return loadometer_load_gross_weight;
  }

  /**
   * Sets the value of the 'loadometer_load_gross_weight' field.
   * @param value the value to set.
   */
  public void setLoadometerLoadGrossWeight(java.lang.Double value) {
    this.loadometer_load_gross_weight = value;
  }

  /**
   * Gets the value of the 'loadometer_load_net_weight' field.
   * @return The value of the 'loadometer_load_net_weight' field.
   */
  public java.lang.Double getLoadometerLoadNetWeight() {
    return loadometer_load_net_weight;
  }

  /**
   * Sets the value of the 'loadometer_load_net_weight' field.
   * @param value the value to set.
   */
  public void setLoadometerLoadNetWeight(java.lang.Double value) {
    this.loadometer_load_net_weight = value;
  }

  /**
   * Gets the value of the 'loadometer_unload_gross_weight' field.
   * @return The value of the 'loadometer_unload_gross_weight' field.
   */
  public java.lang.Double getLoadometerUnloadGrossWeight() {
    return loadometer_unload_gross_weight;
  }

  /**
   * Sets the value of the 'loadometer_unload_gross_weight' field.
   * @param value the value to set.
   */
  public void setLoadometerUnloadGrossWeight(java.lang.Double value) {
    this.loadometer_unload_gross_weight = value;
  }

  /**
   * Gets the value of the 'loadometer_unload_net_weight' field.
   * @return The value of the 'loadometer_unload_net_weight' field.
   */
  public java.lang.Double getLoadometerUnloadNetWeight() {
    return loadometer_unload_net_weight;
  }

  /**
   * Sets the value of the 'loadometer_unload_net_weight' field.
   * @param value the value to set.
   */
  public void setLoadometerUnloadNetWeight(java.lang.Double value) {
    this.loadometer_unload_net_weight = value;
  }

  /**
   * Gets the value of the 'loadometer_load_unload_weight' field.
   * @return The value of the 'loadometer_load_unload_weight' field.
   */
  public java.lang.Double getLoadometerLoadUnloadWeight() {
    return loadometer_load_unload_weight;
  }

  /**
   * Sets the value of the 'loadometer_load_unload_weight' field.
   * @param value the value to set.
   */
  public void setLoadometerLoadUnloadWeight(java.lang.Double value) {
    this.loadometer_load_unload_weight = value;
  }

  /**
   * Gets the value of the 'scan_load_weight' field.
   * @return The value of the 'scan_load_weight' field.
   */
  public java.lang.Double getScanLoadWeight() {
    return scan_load_weight;
  }

  /**
   * Sets the value of the 'scan_load_weight' field.
   * @param value the value to set.
   */
  public void setScanLoadWeight(java.lang.Double value) {
    this.scan_load_weight = value;
  }

  /**
   * Gets the value of the 'load_number' field.
   * @return The value of the 'load_number' field.
   */
  public java.lang.Integer getLoadNumber() {
    return load_number;
  }

  /**
   * Sets the value of the 'load_number' field.
   * @param value the value to set.
   */
  public void setLoadNumber(java.lang.Integer value) {
    this.load_number = value;
  }

  /**
   * Gets the value of the 'scan_unload_weight' field.
   * @return The value of the 'scan_unload_weight' field.
   */
  public java.lang.Double getScanUnloadWeight() {
    return scan_unload_weight;
  }

  /**
   * Sets the value of the 'scan_unload_weight' field.
   * @param value the value to set.
   */
  public void setScanUnloadWeight(java.lang.Double value) {
    this.scan_unload_weight = value;
  }

  /**
   * Gets the value of the 'unload_number' field.
   * @return The value of the 'unload_number' field.
   */
  public java.lang.Integer getUnloadNumber() {
    return unload_number;
  }

  /**
   * Sets the value of the 'unload_number' field.
   * @param value the value to set.
   */
  public void setUnloadNumber(java.lang.Integer value) {
    this.unload_number = value;
  }

  /**
   * Gets the value of the 'database_timestamp' field.
   * @return The value of the 'database_timestamp' field.
   */
  public java.lang.Long getDatabaseTimestamp() {
    return database_timestamp;
  }

  /**
   * Sets the value of the 'database_timestamp' field.
   * @param value the value to set.
   */
  public void setDatabaseTimestamp(java.lang.Long value) {
    this.database_timestamp = value;
  }

  /**
   * Creates a new BeiDouSystem RecordBuilder.
   * @return A new BeiDouSystem RecordBuilder
   */
  public static com.yunda.realtime.avro.BeiDouSystem.Builder newBuilder() {
    return new com.yunda.realtime.avro.BeiDouSystem.Builder();
  }

  /**
   * Creates a new BeiDouSystem RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BeiDouSystem RecordBuilder
   */
  public static com.yunda.realtime.avro.BeiDouSystem.Builder newBuilder(com.yunda.realtime.avro.BeiDouSystem.Builder other) {
    return new com.yunda.realtime.avro.BeiDouSystem.Builder(other);
  }

  /**
   * Creates a new BeiDouSystem RecordBuilder by copying an existing BeiDouSystem instance.
   * @param other The existing instance to copy.
   * @return A new BeiDouSystem RecordBuilder
   */
  public static com.yunda.realtime.avro.BeiDouSystem.Builder newBuilder(com.yunda.realtime.avro.BeiDouSystem other) {
    return new com.yunda.realtime.avro.BeiDouSystem.Builder(other);
  }

  /**
   * RecordBuilder for BeiDouSystem instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BeiDouSystem>
    implements org.apache.avro.data.RecordBuilder<BeiDouSystem> {

    private java.lang.CharSequence depart_proof;
    private java.lang.Integer site_type;
    private java.lang.CharSequence site_encoding;
    private java.lang.Double loadometer_load_gross_weight;
    private java.lang.Double loadometer_load_net_weight;
    private java.lang.Double loadometer_unload_gross_weight;
    private java.lang.Double loadometer_unload_net_weight;
    private java.lang.Double loadometer_load_unload_weight;
    private java.lang.Double scan_load_weight;
    private java.lang.Integer load_number;
    private java.lang.Double scan_unload_weight;
    private java.lang.Integer unload_number;
    private java.lang.Long database_timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yunda.realtime.avro.BeiDouSystem.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.depart_proof)) {
        this.depart_proof = data().deepCopy(fields()[0].schema(), other.depart_proof);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.site_type)) {
        this.site_type = data().deepCopy(fields()[1].schema(), other.site_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.site_encoding)) {
        this.site_encoding = data().deepCopy(fields()[2].schema(), other.site_encoding);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.loadometer_load_gross_weight)) {
        this.loadometer_load_gross_weight = data().deepCopy(fields()[3].schema(), other.loadometer_load_gross_weight);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.loadometer_load_net_weight)) {
        this.loadometer_load_net_weight = data().deepCopy(fields()[4].schema(), other.loadometer_load_net_weight);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.loadometer_unload_gross_weight)) {
        this.loadometer_unload_gross_weight = data().deepCopy(fields()[5].schema(), other.loadometer_unload_gross_weight);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.loadometer_unload_net_weight)) {
        this.loadometer_unload_net_weight = data().deepCopy(fields()[6].schema(), other.loadometer_unload_net_weight);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.loadometer_load_unload_weight)) {
        this.loadometer_load_unload_weight = data().deepCopy(fields()[7].schema(), other.loadometer_load_unload_weight);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.scan_load_weight)) {
        this.scan_load_weight = data().deepCopy(fields()[8].schema(), other.scan_load_weight);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.load_number)) {
        this.load_number = data().deepCopy(fields()[9].schema(), other.load_number);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.scan_unload_weight)) {
        this.scan_unload_weight = data().deepCopy(fields()[10].schema(), other.scan_unload_weight);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.unload_number)) {
        this.unload_number = data().deepCopy(fields()[11].schema(), other.unload_number);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.database_timestamp)) {
        this.database_timestamp = data().deepCopy(fields()[12].schema(), other.database_timestamp);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BeiDouSystem instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yunda.realtime.avro.BeiDouSystem other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.depart_proof)) {
        this.depart_proof = data().deepCopy(fields()[0].schema(), other.depart_proof);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.site_type)) {
        this.site_type = data().deepCopy(fields()[1].schema(), other.site_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.site_encoding)) {
        this.site_encoding = data().deepCopy(fields()[2].schema(), other.site_encoding);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.loadometer_load_gross_weight)) {
        this.loadometer_load_gross_weight = data().deepCopy(fields()[3].schema(), other.loadometer_load_gross_weight);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.loadometer_load_net_weight)) {
        this.loadometer_load_net_weight = data().deepCopy(fields()[4].schema(), other.loadometer_load_net_weight);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.loadometer_unload_gross_weight)) {
        this.loadometer_unload_gross_weight = data().deepCopy(fields()[5].schema(), other.loadometer_unload_gross_weight);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.loadometer_unload_net_weight)) {
        this.loadometer_unload_net_weight = data().deepCopy(fields()[6].schema(), other.loadometer_unload_net_weight);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.loadometer_load_unload_weight)) {
        this.loadometer_load_unload_weight = data().deepCopy(fields()[7].schema(), other.loadometer_load_unload_weight);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.scan_load_weight)) {
        this.scan_load_weight = data().deepCopy(fields()[8].schema(), other.scan_load_weight);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.load_number)) {
        this.load_number = data().deepCopy(fields()[9].schema(), other.load_number);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.scan_unload_weight)) {
        this.scan_unload_weight = data().deepCopy(fields()[10].schema(), other.scan_unload_weight);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.unload_number)) {
        this.unload_number = data().deepCopy(fields()[11].schema(), other.unload_number);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.database_timestamp)) {
        this.database_timestamp = data().deepCopy(fields()[12].schema(), other.database_timestamp);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'depart_proof' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartProof() {
      return depart_proof;
    }

    /**
      * Sets the value of the 'depart_proof' field.
      * @param value The value of 'depart_proof'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setDepartProof(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.depart_proof = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'depart_proof' field has been set.
      * @return True if the 'depart_proof' field has been set, false otherwise.
      */
    public boolean hasDepartProof() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'depart_proof' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearDepartProof() {
      depart_proof = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'site_type' field.
      * @return The value.
      */
    public java.lang.Integer getSiteType() {
      return site_type;
    }

    /**
      * Sets the value of the 'site_type' field.
      * @param value The value of 'site_type'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setSiteType(java.lang.Integer value) {
      validate(fields()[1], value);
      this.site_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'site_type' field has been set.
      * @return True if the 'site_type' field has been set, false otherwise.
      */
    public boolean hasSiteType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'site_type' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearSiteType() {
      site_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'site_encoding' field.
      * @return The value.
      */
    public java.lang.CharSequence getSiteEncoding() {
      return site_encoding;
    }

    /**
      * Sets the value of the 'site_encoding' field.
      * @param value The value of 'site_encoding'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setSiteEncoding(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.site_encoding = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'site_encoding' field has been set.
      * @return True if the 'site_encoding' field has been set, false otherwise.
      */
    public boolean hasSiteEncoding() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'site_encoding' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearSiteEncoding() {
      site_encoding = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadometer_load_gross_weight' field.
      * @return The value.
      */
    public java.lang.Double getLoadometerLoadGrossWeight() {
      return loadometer_load_gross_weight;
    }

    /**
      * Sets the value of the 'loadometer_load_gross_weight' field.
      * @param value The value of 'loadometer_load_gross_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadometerLoadGrossWeight(java.lang.Double value) {
      validate(fields()[3], value);
      this.loadometer_load_gross_weight = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'loadometer_load_gross_weight' field has been set.
      * @return True if the 'loadometer_load_gross_weight' field has been set, false otherwise.
      */
    public boolean hasLoadometerLoadGrossWeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'loadometer_load_gross_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadometerLoadGrossWeight() {
      loadometer_load_gross_weight = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadometer_load_net_weight' field.
      * @return The value.
      */
    public java.lang.Double getLoadometerLoadNetWeight() {
      return loadometer_load_net_weight;
    }

    /**
      * Sets the value of the 'loadometer_load_net_weight' field.
      * @param value The value of 'loadometer_load_net_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadometerLoadNetWeight(java.lang.Double value) {
      validate(fields()[4], value);
      this.loadometer_load_net_weight = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'loadometer_load_net_weight' field has been set.
      * @return True if the 'loadometer_load_net_weight' field has been set, false otherwise.
      */
    public boolean hasLoadometerLoadNetWeight() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'loadometer_load_net_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadometerLoadNetWeight() {
      loadometer_load_net_weight = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadometer_unload_gross_weight' field.
      * @return The value.
      */
    public java.lang.Double getLoadometerUnloadGrossWeight() {
      return loadometer_unload_gross_weight;
    }

    /**
      * Sets the value of the 'loadometer_unload_gross_weight' field.
      * @param value The value of 'loadometer_unload_gross_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadometerUnloadGrossWeight(java.lang.Double value) {
      validate(fields()[5], value);
      this.loadometer_unload_gross_weight = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'loadometer_unload_gross_weight' field has been set.
      * @return True if the 'loadometer_unload_gross_weight' field has been set, false otherwise.
      */
    public boolean hasLoadometerUnloadGrossWeight() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'loadometer_unload_gross_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadometerUnloadGrossWeight() {
      loadometer_unload_gross_weight = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadometer_unload_net_weight' field.
      * @return The value.
      */
    public java.lang.Double getLoadometerUnloadNetWeight() {
      return loadometer_unload_net_weight;
    }

    /**
      * Sets the value of the 'loadometer_unload_net_weight' field.
      * @param value The value of 'loadometer_unload_net_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadometerUnloadNetWeight(java.lang.Double value) {
      validate(fields()[6], value);
      this.loadometer_unload_net_weight = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'loadometer_unload_net_weight' field has been set.
      * @return True if the 'loadometer_unload_net_weight' field has been set, false otherwise.
      */
    public boolean hasLoadometerUnloadNetWeight() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'loadometer_unload_net_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadometerUnloadNetWeight() {
      loadometer_unload_net_weight = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadometer_load_unload_weight' field.
      * @return The value.
      */
    public java.lang.Double getLoadometerLoadUnloadWeight() {
      return loadometer_load_unload_weight;
    }

    /**
      * Sets the value of the 'loadometer_load_unload_weight' field.
      * @param value The value of 'loadometer_load_unload_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadometerLoadUnloadWeight(java.lang.Double value) {
      validate(fields()[7], value);
      this.loadometer_load_unload_weight = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'loadometer_load_unload_weight' field has been set.
      * @return True if the 'loadometer_load_unload_weight' field has been set, false otherwise.
      */
    public boolean hasLoadometerLoadUnloadWeight() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'loadometer_load_unload_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadometerLoadUnloadWeight() {
      loadometer_load_unload_weight = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'scan_load_weight' field.
      * @return The value.
      */
    public java.lang.Double getScanLoadWeight() {
      return scan_load_weight;
    }

    /**
      * Sets the value of the 'scan_load_weight' field.
      * @param value The value of 'scan_load_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setScanLoadWeight(java.lang.Double value) {
      validate(fields()[8], value);
      this.scan_load_weight = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'scan_load_weight' field has been set.
      * @return True if the 'scan_load_weight' field has been set, false otherwise.
      */
    public boolean hasScanLoadWeight() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'scan_load_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearScanLoadWeight() {
      scan_load_weight = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'load_number' field.
      * @return The value.
      */
    public java.lang.Integer getLoadNumber() {
      return load_number;
    }

    /**
      * Sets the value of the 'load_number' field.
      * @param value The value of 'load_number'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setLoadNumber(java.lang.Integer value) {
      validate(fields()[9], value);
      this.load_number = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'load_number' field has been set.
      * @return True if the 'load_number' field has been set, false otherwise.
      */
    public boolean hasLoadNumber() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'load_number' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearLoadNumber() {
      load_number = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'scan_unload_weight' field.
      * @return The value.
      */
    public java.lang.Double getScanUnloadWeight() {
      return scan_unload_weight;
    }

    /**
      * Sets the value of the 'scan_unload_weight' field.
      * @param value The value of 'scan_unload_weight'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setScanUnloadWeight(java.lang.Double value) {
      validate(fields()[10], value);
      this.scan_unload_weight = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'scan_unload_weight' field has been set.
      * @return True if the 'scan_unload_weight' field has been set, false otherwise.
      */
    public boolean hasScanUnloadWeight() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'scan_unload_weight' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearScanUnloadWeight() {
      scan_unload_weight = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'unload_number' field.
      * @return The value.
      */
    public java.lang.Integer getUnloadNumber() {
      return unload_number;
    }

    /**
      * Sets the value of the 'unload_number' field.
      * @param value The value of 'unload_number'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setUnloadNumber(java.lang.Integer value) {
      validate(fields()[11], value);
      this.unload_number = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'unload_number' field has been set.
      * @return True if the 'unload_number' field has been set, false otherwise.
      */
    public boolean hasUnloadNumber() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'unload_number' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearUnloadNumber() {
      unload_number = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'database_timestamp' field.
      * @return The value.
      */
    public java.lang.Long getDatabaseTimestamp() {
      return database_timestamp;
    }

    /**
      * Sets the value of the 'database_timestamp' field.
      * @param value The value of 'database_timestamp'.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder setDatabaseTimestamp(java.lang.Long value) {
      validate(fields()[12], value);
      this.database_timestamp = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'database_timestamp' field has been set.
      * @return True if the 'database_timestamp' field has been set, false otherwise.
      */
    public boolean hasDatabaseTimestamp() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'database_timestamp' field.
      * @return This builder.
      */
    public com.yunda.realtime.avro.BeiDouSystem.Builder clearDatabaseTimestamp() {
      database_timestamp = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BeiDouSystem build() {
      try {
        BeiDouSystem record = new BeiDouSystem();
        record.depart_proof = fieldSetFlags()[0] ? this.depart_proof : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.site_type = fieldSetFlags()[1] ? this.site_type : (java.lang.Integer) defaultValue(fields()[1]);
        record.site_encoding = fieldSetFlags()[2] ? this.site_encoding : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.loadometer_load_gross_weight = fieldSetFlags()[3] ? this.loadometer_load_gross_weight : (java.lang.Double) defaultValue(fields()[3]);
        record.loadometer_load_net_weight = fieldSetFlags()[4] ? this.loadometer_load_net_weight : (java.lang.Double) defaultValue(fields()[4]);
        record.loadometer_unload_gross_weight = fieldSetFlags()[5] ? this.loadometer_unload_gross_weight : (java.lang.Double) defaultValue(fields()[5]);
        record.loadometer_unload_net_weight = fieldSetFlags()[6] ? this.loadometer_unload_net_weight : (java.lang.Double) defaultValue(fields()[6]);
        record.loadometer_load_unload_weight = fieldSetFlags()[7] ? this.loadometer_load_unload_weight : (java.lang.Double) defaultValue(fields()[7]);
        record.scan_load_weight = fieldSetFlags()[8] ? this.scan_load_weight : (java.lang.Double) defaultValue(fields()[8]);
        record.load_number = fieldSetFlags()[9] ? this.load_number : (java.lang.Integer) defaultValue(fields()[9]);
        record.scan_unload_weight = fieldSetFlags()[10] ? this.scan_unload_weight : (java.lang.Double) defaultValue(fields()[10]);
        record.unload_number = fieldSetFlags()[11] ? this.unload_number : (java.lang.Integer) defaultValue(fields()[11]);
        record.database_timestamp = fieldSetFlags()[12] ? this.database_timestamp : (java.lang.Long) defaultValue(fields()[12]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BeiDouSystem>
    WRITER$ = (org.apache.avro.io.DatumWriter<BeiDouSystem>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BeiDouSystem>
    READER$ = (org.apache.avro.io.DatumReader<BeiDouSystem>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
